### PR TITLE
Move to Lerna

### PR DESCRIPTION
**Pull request by ChristopherBiscardi**
Lays the groundwork for a port to lerna, which makes it easier to support things like Preact (#194) as additional packages and splits up the current packages (#83). PRing for visibility and comment.

* Currently leaving "global dev tools" in root package.json (karma, eslint)
* Karma tests have been split per-package, but are still triggered via `npm test`

Right now this will install all global dev tools, bootstrap the packages and run the karma tests:

```shell
npm i
lerna bootstrap
npm test
```

Bootstrapping builds and links `glamor` into three other packages for tests, providing a nice proving point for how cross-project dependencies will work when developing.

current packages are:

```
babel-plugin-glamor glamor-jsxstyle     glamor-reset
glamor              glamor-ous          glamor-styled
glamor-aphrodite    glamor-raw-css      glamor-utils
glamor-autoprefixer glamor-react
```

### CODE REVIEW

**Comment by donaldpipowitch** [comment]
I hope we can review that next week. Thank you so far!

**Comment by ChristopherBiscardi** [comment]
@donaldpipowitch @threepointone Since this is a fairly impactful PR, what can I do to make this easier on you all? Happy to write more documentation, go into more detail on what's happening in the PR, etc.

**Comment by donaldpipowitch** [comment]
Coincidentally I looked into your PR some hours ago and I'd like to use it as a new starting point for a new major version of glamor. I just recently got push rights to glamor so I don't want to go all in without asking @threepointone for some higher picture, because he already started a `v3` branch some months ago.

I sketched out what I would like to do with @otbe here https://github.com/threepointone/glamor/issues/83#issuecomment-278260043. As far as I understand @threepointone would like to take a little break from this project at least for now (- please clarify this, if I misunderstood this). So I _guess_ he'll be fine with https://github.com/threepointone/glamor/issues/83#issuecomment-278260043. If he doesn't respond in the next days I'll probably just create a `new-v3` branch or something like that and just start with the ideas from https://github.com/threepointone/glamor/issues/83#issuecomment-278260043 and see how far we can get with that.

**Comment by ChristopherBiscardi** [comment]
@donaldpipowitch Sounds good. I was under the impression that most of the v3 branch stuff was merged into master (the v3 branch is 122 commits behind and 0 ahead).

I'm happy to take on more with regards to #83 and a 3.0 push. My previous thinking was that splitting the packages up was the most impactful thing I could do for 3.0, then could move more easily on the rest. I also use TypeScript at work these days, so would by happy to help port the codebase.

**Comment by donaldpipowitch** [comment]
>  I was under the impression that most of the v3 branch stuff was merged into master (the v3 branch is 122 commits behind and 0 ahead).

Yeah, that is my impression, too. Good to hear the same from someone else. I guess we can just remove the old branch then :)

**Comment by donaldpipowitch** [comment]
@ChristopherBiscardi I've created a new `v3` branch based on your PR. I cherry picked two commits (only for docs) since the beginning of your PR - I think these two were the only new ones. I also added a `postinstall` to bootstrap lerna. I have little to no experience with lerna, so maybe this is some bad practice or something, but from my point of view it looked useful. I also updated the `.gitignore` to match the new project structure.

I hoped GitHub would notice that a new branch based on the PR exists and it would offer me to close this PR. Sadly this is not the case, so I'll close this PR manually. But your commits and history is preserved in the `v3` branch of course which will be merged into master someday when https://github.com/threepointone/glamor/issues/83 is finished.

Going on from here I'll try to write a small migration guide to the new package structure, deprecate the old modules and publish a new v2 patch version and a v3 prerelease. 👍

**Pull request closed without merging**
