### PR TITLE
[WIP] ignore empty and falsy values

### PR DESCRIPTION
**Pull request by vdanchenkov**
This PR is a natural extension of #41 with fixes for most of #51 problems. I'm sending it in one shot as they are related.

Included:

1. Proper tests for falsy values handling.
2. Falsy values filtering for all functions in the main module. 
3. Style() and friends return {} if there is nothing to add to stylesheet.

Todo:

1. clean clean.js, check performance
2. more tests
3. more docs?

### CODE REVIEW

**Comment by threepointone** [comment]
Thanks a bunch for this! I'm swamped this week with some other stuff, but I should merge it in by the weekend. I'm not *completely* sold on returning an empty object for an empty style, but maybe I'll warm up to it by the weekend. Thanks again!

**Comment by vdanchenkov** [comment]
@threepointone Please, have your time. I'm not bound to idea to return empty objects, but I had to do something about empty styles as conditional styling would make empty styles more frequent and behaviour was not consistent. Removing empty styles looked like an easier to implement and more general option for me and I have no idea why would anyone like to keep empty rules in stylesheet.

**Comment by threepointone** [comment]
merging this in, but I'll take a couple of days to try and break it :) still not *fully* convinced about empty objects, but I'll give it some time and see if it grows on me with usage. 

Thanks for the excellent work, I'm so happy you did this.

**Comment by threepointone** [comment]
will publish by friday tentatively.

**Comment by threepointone** [comment]
this is live in 2.15.6. sorry for the delay!

**Pull request merged**
