### PR TITLE
Reduce granularity of reset tests

### LINKED ISSUE #210: Tests for glamor-reset broken (v3)
Tests for glamor-reset are broken caused by subtle browser differences. You can reproduce this by change PhantomJS to Chrome in https://github.com/threepointone/glamor/blob/v3/karma.conf.js#L68 and run tests for glamor-reset.

Any ideas how to fix this? :)

cc @ChristopherBiscardi

### PR DESCRIPTION
**Pull request by ChristopherBiscardi**
Different browsers, Chrome in this case, result in different
outputs. Since these are not bugs, but rather behavioral differences
between browsers and we are not maintaining the actual rulesets (just
glamor's ability to insert them), the tests have been changed to
detect the count of rules inserted instead of string matching rule
output.

closes #210

### CODE REVIEW

**Comment by ChristopherBiscardi** [comment]
cc @otbe

**Comment by otbe** [comment]
I guess it still fails for FF :/

I run ```ALL=true npm run test```. I don't know if its the same for FF 43 which is used by glamors BS config...

```
FAILED TESTS:
  glamor-reset
    ✖ inserts an appropriate number of normalize styles
      Firefox 51.0.0 (Mac OS X 10.12.0)
    Expected 41 to equal 42
    assert@packages/glamor-reset/tests/index.js:4585:9
    toEqual@packages/glamor-reset/tests/index.js:9852:10
    @packages/glamor-reset/tests/index.js:28796:5


  glamor-reset:production
    ✖ inserts an appropriate number of normalize styles
      Firefox 51.0.0 (Mac OS X 10.12.0)
    Expected 41 to equal 42
    assert@packages/glamor-reset/tests/production.js:4585:9
    toEqual@packages/glamor-reset/tests/production.js:9852:10
    @packages/glamor-reset/tests/production.js:36836:5
```

<details><summary>Inserted rules by FF 51</summary>
<code><pre>html { font-family: sans-serif; line-height: 1.15; }
body { margin: 0px; }
article, aside, footer, header, nav, section { display: block; }
h1 { font-size: 2em; margin: 0.67em 0px; }
figcaption, figure, main { display: block; }
figure { margin: 1em 40px; }
hr { box-sizing: content-box; height: 0px; overflow: visible; }
pre { font-family: monospace,monospace; font-size: 1em; }
a { background-color: transparent; }
a:active, a:hover { outline-width: 0px; }
abbr[title] { border-bottom: medium none; text-decoration: underline dotted; }
b, strong { font-weight: inherit; }
b, strong { font-weight: bolder; }
code, kbd, samp { font-family: monospace,monospace; font-size: 1em; }
dfn { font-style: italic; }
mark { background-color: rgb(255, 255, 0); color: rgb(0, 0, 0); }
small { font-size: 80%; }
sub, sup { font-size: 75%; line-height: 0; position: relative; vertical-align: baseline; }
sub { bottom: -0.25em; }
sup { top: -0.5em; }
audio, video { display: inline-block; }
audio:not([controls]) { display: none; height: 0px; }
img { border-style: none; }
svg:not(:root) { overflow: hidden; }
button, input, optgroup, select, textarea { font-family: sans-serif; font-size: 100%; line-height: 1.15; margin: 0px; }
button, input { overflow: visible; }
button, select { text-transform: none; }
button, html [type="button"], [type="reset"], [type="submit"] {  }
button::-moz-focus-inner, [type="button"]::-moz-focus-inner, [type="reset"]::-moz-focus-inner, [type="submit"]::-moz-focus-inner { border
-style: none; padding: 0px; }
button:-moz-focusring, [type="button"]:-moz-focusring, [type="reset"]:-moz-focusring, [type="submit"]:-moz-focusring { outline: 1px dotte
d buttontext; }
fieldset { border: 1px solid rgb(192, 192, 192); margin: 0px 2px; padding: 0.35em 0.625em 0.75em; }
legend { box-sizing: border-box; color: inherit; display: table; max-width: 100%; padding: 0px; white-space: normal; }
progress { display: inline-block; vertical-align: baseline; }
textarea { overflow: auto; }
[type="checkbox"], [type="radio"] { box-sizing: border-box; padding: 0px; }
[type="search"] { outline-offset: -2px; }
details, menu { display: block; }
summary { display: list-item; }
canvas { display: inline-block; }
template { display: none; }
[hidden] { display: none; }
</pre></code></details>

Maybe we should drop tests? Dunno....

**Comment by ChristopherBiscardi** [comment]
ugh, of course. because the extra rule is `::-webkit-file-upload-button`.

**Comment by otbe** [comment]
```
expect(styleSheet.rules().length).toBeGreaterThanOrEqualTo(42 - 1);
```
😅

**Comment by donaldpipowitch** [comment]
> Maybe we should drop tests? Dunno...

Maybe that would be okay'ish for now. I don't know if this test is that useful.

Maybe it would be a better idea to create a webpack loader which reads _any_ css and turns it into a glamorized version anyway. That way we don't need to extract every rule manually.

I'd be fine if we just remove the tests for now.

**Comment by ChristopherBiscardi** [comment]
ok, I removed the tests completely for now. The production test was only there to be sure we weren't inserting rules in batches (because they would get dropped in speedy mode #192). I think the functionality of `insertRule` should be covered by core glamor tests and the normalize functionality should be handled by the normalize.css project. That really leaves nothing to be done in tests here except not insert rules in batches. Maybe we can write an eslint rule in the future for glamor inserts.

> Maybe it would be a better idea to create a webpack loader which reads any css and turns it into a glamorized version anyway. That way we don't need to extract every rule manually.

Definitely interesting. Then we don't have to maintain glamor-normalize, glamor-sanitize, glamor-bootstrap-whatever, etc type packages.

**Comment by otbe** [comment]
👍

**Pull request merged**
