### PR TITLE
add support for css()

### PR DESCRIPTION
**Pull request by otbe**

### CODE REVIEW

**Comment by threepointone** [comment]
thanks again!

**Comment by threepointone** [comment]
yo @otbe, have you considered copying the typings for styles from https://github.com/typestyle/typestyle/blob/master/src/css.d.ts? would be cool if it worked.

**Comment by otbe** [comment]
@donaldpipowitch asked already @basarat for this :)

**Comment by donaldpipowitch** [comment]
@basarat said that he maybe looks for a nice way to solve that when his lib goes `1.0.0`. I'd probably wait until then.

**Comment by threepointone** [comment]
👍🏽 looking forward to it, should be fun

**Pull request merged**
