### PR TITLE
pulls @import rules to the top of the stylesheet

### LINKED ISSUE #142: insertRule() should carefully handle @imports
Hi @threepointone,

```@impot url()``` rules must be the first entries in every stylesheet. So I think insertRule should handle it properly (prepending instead of appending :)).

Example
```
insertRule(`html{font-size: ${defaultFontSize};}`);
insertRule('@import url(https://fonts.googleapis.com/css?family=Merriweather+Sans:300,300i,400,400i|Merriweather:300,300i,400,400i|Lato:300,300i,400,400i,700,700i);');
```
UseCase: in some common modules we define this import, but we can not guarantee that it will be executed in a proper order.

### PR DESCRIPTION
**Pull request by otbe**
fixes #142 

Note: this is a naive first attempt to fix this issue, because its breaks our production SPAs ATM :)

### CODE REVIEW

**Comment by threepointone** [comment]
It seems to break on ff 43 

Firefox 43.0.0 (Windows 10 0.0.0) StyleSheet prepends @import rules FAILED
	A parameter or an operation is not supported by the underlying object
	rules/<@index.js:10554:89
	rules@index.js:10553:5
	@index.js:55840:17

https://travis-ci.org/threepointone/glamor/builds/182789081

I'll have a look in a bit, unless you have an idea

**Comment by otbe** [comment]
Mh thats strange. I tested it on ff 50 and (now) 43 and it works in dev/speedy mode for a real project, but fails in the karma test.

Its related to this line:
```
tag.insertBefore(document.createTextNode(rule), tag.firstChild)
```
If I change ```tag.firstChild``` to ```null``` it stops throwing. ```tag.firstChild``` contains a text node in all browsers (phantom, chrome and FF) but I really I have no idea why it throws this error for firefox :/

**Comment by threepointone** [comment]
Don't worry, I'll have a little look, just FYI it means guy not release
today tho :(

**Comment by otbe** [comment]
It works for me in this [fiddle](https://jsfiddle.net/pevptdmf/1) in ff43&ff50. Really weird :/
Maybe I will look into it this afternoon :)

**Comment by threepointone** [comment]
ok I think I figured this out. adding an import rule in firefox makes cssRules be an indeterminate object for a tick, while it finishes parsing. in the test, we read rules() syncly, which causes this error. the fix is simply to fix the test.

**Pull request merged**
