### PR TITLE
Typings for glamor-server & glamor rehydrate function

### PR DESCRIPTION
**Pull request by manugill**
Hey, just added quick typings for these, let me know if I've missed something.

### CODE REVIEW

**Comment by sammkj** [comment]
Can this be merged? Need this desperately

**Comment by ChristopherBiscardi** [comment]
cc/ @donaldpipowitch Looks fine to me but we'd need a release.

**Comment by donaldpipowitch** [comment]
Sorry, for being a little bit slow lately. I don't find a lot of spare time currently. 

> but we'd need a release.

Yeah, that could be a problem, because #231 was already merged and we haven't finished #229. I _really_ would like to finish #229 to not publish a version with removed APIs and without updated migration guide and so on.

The good thing is, that this problem can be workaround quite easily currently. Everyone with a TypeScript project could just add this to there projects:

```ts
declare module 'glamor-server' {
  export function renderStatic(fn: () => string): object
  export function renderStaticOptimized(fn: () => string): object
}
```

IMHO this would be a "good enough" solution until #229 is finished. Probably not very satisfying, but it hopefully should be a short annoyance.

Starting with next week we actually have a new intern here at @Mercateo and I currently plan that he could work on  #229.

**Comment by ChristopherBiscardi** [comment]
yeah, given the status of #234 and #242 for example, some API stuff feels in-limbo.

**Comment by donaldpipowitch** [comment]
`glamor` is now written in TypeScript and contains `rehydrate`. If you want typings for `glamor-server` we'd be happy to see a PR with a rewrite to TypeScript ❤️  Thank you all.

**Pull request closed without merging**
