### PR TITLE
add order-agnostic sha1 hash

### PR DESCRIPTION
**Pull request by amir-arad**
as described in #259 
added sha1 for better hashing
added json loader to webpack
couldn't test locally for some reason, so that's an optimistic PR

### CODE REVIEW

**Comment by amir-arad** [comment]
ok, got it, I need to figure out testing locally :(

**Comment by threepointone** [comment]
npm test should run tests?
and npm start should start a webpack dev server with examples/index.js

**Comment by amir-arad** [comment]
thanks, what I meant to say is that I got some mysterious karma errors when I try to run the tests

**Comment by threepointone** [comment]
yeah I fixed that issue, should be fine now

**Comment by threepointone** [comment]
warning in advance, I see no real reason to use sha-1, so might not approve this PR. cheers :)

**Comment by amir-arad** [comment]
My assumption is that the sha1 solution will perform better due to better cache hits in real life scenarios. 

so, what are the parameters for a sound hashing solution?

**Comment by threepointone** [comment]
in practice, styles are pretty stable and in the same positions, so it's really an overoptimization (and if I'm eyeballing this correctly, it'll also increase the bundle size). 

Indeed, I'd personally like to replace the json stringify with a simple flatten/concat, but am wary of doing so because it'll likely break a bunch of tests for consumers. 

So I'm just trying to be pragmatic, that's all. Willing to be convinced, but needs to be usecase driven.

**Comment by amir-arad** [comment]
I'm not too familiar with the use-cases of glamor. That's why I started by asking for performance metrics (in #259)

I really can't make a good case that this feature is not an over-optimization without metrics, as there obviously is a trade-off between different performance aspects. 

smallest sha1 I found was [574 Bytes of code](https://github.com/jbt/js-crypto/blob/master/sha1-min.js)

**Comment by threepointone** [comment]
I apologise, I didn't mean to discourage, and can see how it came off that way. Please carry on with the PR, and we'll discuss it on the merits you've outlined.

**Pull request closed without merging**
