### PR TITLE
remove helpers #229

### PR DESCRIPTION
**Pull request by ChristopherBiscardi**
There's a couple of failing tests in `packages/glamor` around falsey value handling but otherwise should be fine.

Reflects the consolidation discussion in #229

screen shot 2017-03-27 at 4 32 39 pm

### CODE REVIEW

**Comment by donaldpipowitch** [comment]
Oh wow, sweet! I hope I can look into this soon.

**Comment by donaldpipowitch** [comment]
Finally found time to look into this PR ❤️ 

The "two" tests which fail are [this one](https://github.com/threepointone/glamor/pull/231/commits/abea0304a5d5d97c34bd61550a91fb7e01db8e10#diff-689a045246cb431763d58b74320be4b1R564) and [this one](https://github.com/threepointone/glamor/pull/231/commits/abea0304a5d5d97c34bd61550a91fb7e01db8e10#diff-689a045246cb431763d58b74320be4b1R569). AFAIK they test the same thing and you can reduce both tests to one test which looks like this:

```
      css,
      [ {'.foo & .bar': { fontSize: 10, color: falsy }} ],
      [ {'.foo & .bar': { fontSize: 10 }} ]
```

Just added `.foo & .bar` to make clear this is about a selector.

**Comment by donaldpipowitch** [comment]
However other tests are now failing for me. Need to look into that later...

**Comment by ChristopherBiscardi** [comment]
> However other tests are failing for me, too

Which ones? Other than the `null, false, undefined` loop for those two `check` tests everything is passing for me locally.

---

I updated the failing test to remove the redundancy. Seems like we have a "real" failing test for css(). Going to have to look into that more.

**Comment by donaldpipowitch** [comment]
It should be 

```diff
-      [ '.foo & .bar', { fontSize: 10, color: falsy } ],
-      [ '.foo & .bar', { fontSize: 10 } ]
+      [ {'.foo & .bar': { fontSize: 10, color: falsy }} ],
+      [ {'.foo & .bar': { fontSize: 10 }} ]
```

or am I wrong? After that the _falsy_ tests work. The test that now errors is 

```
  glamor-jsxstyle
    ✖ exposes a View component

Finished in 0.014 secs / 0.005 secs

SUMMARY:
✔ 0 tests completed
✖ 1 test failed

FAILED TESTS:
  glamor-jsxstyle
    ✖ exposes a View component
      PhantomJS 2.1.1 (Mac OS X 0.0.0)
    undefined is not a constructor (evaluating '__WEBPACK_IMPORTED_MODULE_2_glamor__[key](combinedProps[key])')
```

**Comment by donaldpipowitch** [comment]
This is [the other failing test](https://github.com/ChristopherBiscardi/glamor/blob/f44738273b02edc702d301ef92b275ce48becbfd/packages/glamor-jsxstyle/tests/index.js#L23) :) Not sure how to handle this one. Maybe glamor-jsxstyle is a bit pointless now...?

**Comment by donaldpipowitch** [comment]
Maybe the `glamor-jsxstyle` test should be skipped for now and we'll discuss, if we want to remove support for this package completely?

**Comment by ChristopherBiscardi** [comment]
now skipping the jsxstyle tests and fixed a couple other issues that popped up.

**Comment by ChristopherBiscardi** [comment]
@kentcdodds Just released [glamorous](https://github.com/kentcdodds/glamorous) which includes jsxstyle type functionality. I think we can kill our current implementation and recommend his instead if people want jsxstyle.

**Comment by ChristopherBiscardi** [comment]
On a related note, we may also want to rename `glamor-ous` while we have the chance 😂  before the official 3.0 release. It's skeleton based anyway, so maybe just glamor-skeleton would be better. http://getskeleton.com/

**Comment by donaldpipowitch** [comment]
Merged 🎉 

I like your ideas. Will move the discussion to https://github.com/threepointone/glamor/issues/83 👍

**Pull request merged**
