### PR TITLE
experimental support for classnames(!!!)

### PR DESCRIPTION
**Pull request by threepointone**
`toString()` to the rescueeeeeee

basically, the 'rule' object converts to a classname when treated as a string, and we add that classname to the same css we add for data attributes. BOOM.

### CODE REVIEW

**Comment by otbe** [comment]
Have to pass around some links as strings like:
```
const link = `<a class="${style(linkInlineStyle).toString()}"> target="_blank" href="foo">`;
```

```toString()``` is here my only option, isnt it?

**Comment by threepointone** [comment]
@otbe it should coerce by itself, the following works - 
```jsx
const link = `<a class="${style(linkInlineStyle)}" target="_blank" href="foo">bar</a>`
```

**Comment by otbe** [comment]
Yeah for sure. It was copy&pasted for this small example. This will work after you release this feature!?

Thanks!

**Comment by threepointone** [comment]
Yes, that's the idea! I'll take a day or so to test it out and release

**Comment by slorber** [comment]
Nice

Will the putput css look like this?

```
.xyzhash, data-xyzhash {
   css rules
}
```

**Comment by threepointone** [comment]
Yup, exactly.

**Comment by threepointone** [comment]
this is live in 2.17.0.

**Pull request merged**
