### PR TITLE
Fix placeholder support

### PR DESCRIPTION
**Pull request by fhelwanger**
This fix this issue: https://github.com/threepointone/glamor/issues/14#issuecomment-270473786

### CODE REVIEW

**Comment by threepointone** [comment]
this looks just fine, thank you very much! I'll merge it in for now, will release through the weekend sometime.

**Comment by fhelwanger** [comment]
@threepointone sorry to bother you, but do you know when the next version will be released?

**Comment by threepointone** [comment]
Sorry for the delay, I'll pub within the next 2 hours.

**Comment by threepointone** [comment]
sorry for the delay, this is live in 2.20.22

**Comment by fhelwanger** [comment]
No problem, thanks 😉

**Pull request merged**
