### PR TITLE
added deprecation warnings

### PR DESCRIPTION
**Pull request by donaldpipowitch**
@otbe Should this be enough to add deprecation warnings for v2?

### CODE REVIEW

**Comment by otbe** [comment]
Any reason why you check for ```process.env.NODE_ENV === 'development' || !process.env.NODE_ENV```? I wonder if it would be better to check for ```production``` only like react does it internally  ¯\_(ツ)_/¯

Do we want to add deprecation warnings for ```style()```, ```merge()``` and so on in this step?

**Comment by donaldpipowitch** [comment]
> Any reason why you check for process.env.NODE_ENV === 'development' || !process.env.NODE_ENV?

Yeah, I copied it from here: https://github.com/threepointone/glamor/blob/master/src/index.js#L28 😄 I prefer `process.env.NODE_ENV === 'production'`, too, and probably would do that in our TS rewrite. But I thought that should work for v2 users for now as well, because it is used elsewhere already.

> Do we want to add deprecation warnings for style(), merge() and so on in this step?

No, I'd like to do that in a different step and as its own release.

**Comment by donaldpipowitch** [comment]
Can this be merged?

**Comment by otbe** [comment]
LGTM

**Pull request merged**
